Repository BirthdayCafe/Birca_Backend, pull requests merged in 2024-02, with the labels that each got.

#14 [FEAT] 아티스트 그룹 조회 및 아티스트 그룹의 아티스트 조회 기능 구현
  .gitignore
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/command/artist/domain/ArtistGroup.java
  src/main/java/com/birca/bircabackend/query/controller/ArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/dto/ArtistGroupResponse.java
  src/main/java/com/birca/bircabackend/query/dto/ArtistResponse.java
  src/main/java/com/birca/bircabackend/query/dto/PagingParams.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistGroupDynamicRepository.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistGroupDynamicRepositoryImpl.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistGroupQueryRepository.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistQueryRepository.java
  src/main/java/com/birca/bircabackend/query/repository/DynamicBooleanBuilder.java
  src/main/java/com/birca/bircabackend/query/repository/config/QuerydslConfig.java
  src/main/java/com/birca/bircabackend/query/service/ArtistGroupQueryService.java
  src/main/java/com/birca/bircabackend/query/service/ArtistQueryService.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/birca/bircabackend/query/acceptance/ArtistQueryAcceptanceTest.java
  src/test/java/com/birca/bircabackend/query/controller/ArtistQueryControllerTest.java
  src/test/java/com/birca/bircabackend/query/service/ArtistGroupQueryServiceTest.java
  src/test/java/com/birca/bircabackend/query/service/ArtistQueryServiceTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/fixture/artist-fixture.sql
Labels: FEAT

#16 [FEAT] 관심 아티스트 등록 및 최애 아티스트 등록 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/command/artist/application/ArtistService.java
  src/main/java/com/birca/bircabackend/command/artist/domain/ArtistRepository.java
  src/main/java/com/birca/bircabackend/command/artist/domain/FavoriteArtist.java
  src/main/java/com/birca/bircabackend/command/artist/domain/FavoriteArtistRepository.java
  src/main/java/com/birca/bircabackend/command/artist/domain/InterestArtist.java
  src/main/java/com/birca/bircabackend/command/artist/domain/InterestArtistBulkSaveRepository.java
  src/main/java/com/birca/bircabackend/command/artist/domain/InterestArtistRegisterValidator.java
  src/main/java/com/birca/bircabackend/command/artist/domain/InterestArtistRepository.java
  src/main/java/com/birca/bircabackend/command/artist/dto/FavoriteArtistRequest.java
  src/main/java/com/birca/bircabackend/command/artist/dto/InterestArtistRequest.java
  src/main/java/com/birca/bircabackend/command/artist/exception/ArtistErrorCode.java
  src/main/java/com/birca/bircabackend/command/artist/infrastructure/InterestArtistBulkSaveRepositoryImpl.java
  src/main/java/com/birca/bircabackend/command/artist/presentation/ArtistController.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/birca/bircabackend/command/artist/acceptance/ArtistAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/artist/application/ArtistServiceTest.java
  src/test/java/com/birca/bircabackend/command/artist/presentation/ArtistControllerTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/fixture/artist-fixture.sql
Labels: FEAT

#19 [FEAT] 카카오 로그인 구현
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/BircaBackendApplication.java
  src/main/java/com/birca/bircabackend/command/artist/application/ArtistService.java
  src/main/java/com/birca/bircabackend/command/artist/presentation/ArtistController.java
  src/main/java/com/birca/bircabackend/command/auth/AuthConfig.java
  src/main/java/com/birca/bircabackend/command/auth/application/AuthFacade.java
  src/main/java/com/birca/bircabackend/command/auth/application/AuthService.java
  src/main/java/com/birca/bircabackend/command/auth/application/MemberAuthRepository.java
  src/main/java/com/birca/bircabackend/command/auth/application/oauth/OAuthMember.java
  src/main/java/com/birca/bircabackend/command/auth/application/oauth/OAuthProvider.java
  src/main/java/com/birca/bircabackend/command/auth/application/oauth/OAuthProviderFactory.java
  src/main/java/com/birca/bircabackend/command/auth/application/token/JwtTokenExtractor.java
  src/main/java/com/birca/bircabackend/command/auth/application/token/JwtTokenProvider.java
  src/main/java/com/birca/bircabackend/command/auth/application/token/TokenPayload.java
  src/main/java/com/birca/bircabackend/command/auth/authorization/LoginMember.java
  src/main/java/com/birca/bircabackend/command/auth/authorization/LoginMemberArgumentResolver.java
  src/main/java/com/birca/bircabackend/command/auth/authorization/RequiredLogin.java
  src/main/java/com/birca/bircabackend/command/auth/authorization/RequiredLoginInterceptor.java
  src/main/java/com/birca/bircabackend/command/auth/dto/LoginRequest.java
  src/main/java/com/birca/bircabackend/command/auth/dto/LoginResponse.java
  src/main/java/com/birca/bircabackend/command/auth/exception/AuthErrorCode.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/kakao/KakaoAuthApi.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/kakao/KakaoOAuthProvider.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/kakao/KakaoUserResponse.java
  src/main/java/com/birca/bircabackend/command/auth/login/LoginMember.java
  src/main/java/com/birca/bircabackend/command/auth/presentation/AuthController.java
  src/main/java/com/birca/bircabackend/command/member/application/MemberService.java
  src/main/java/com/birca/bircabackend/command/member/domain/Member.java
  src/main/java/com/birca/bircabackend/command/member/domain/MemberRepository.java
  src/main/java/com/birca/bircabackend/command/member/exception/MemberErrorCode.java
  src/main/java/com/birca/bircabackend/command/member/presentation/MemberController.java
  src/main/java/com/birca/bircabackend/query/controller/ArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/controller/MemberQueryController.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/birca/bircabackend/command/artist/application/ArtistServiceTest.java
  src/test/java/com/birca/bircabackend/command/auth/RequiredLoginTest.java
  src/test/java/com/birca/bircabackend/command/auth/RequiredLoginTestController.java
  src/test/java/com/birca/bircabackend/command/auth/acceptance/AuthAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/auth/application/AuthServiceTest.java
  src/test/java/com/birca/bircabackend/command/auth/presentation/AuthControllerTest.java
  src/test/java/com/birca/bircabackend/command/auth/token/JwtTokenExtractorTest.java
  src/test/java/com/birca/bircabackend/command/auth/token/JwtTokenProviderTest.java
  src/test/java/com/birca/bircabackend/command/member/application/MemberServiceTest.java
  src/test/java/com/birca/bircabackend/command/member/domain/MemberTest.java
  src/test/java/com/birca/bircabackend/support/TestBearerTokenProvider.java
  src/test/java/com/birca/bircabackend/support/enviroment/AcceptanceTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/MockOAuthEnvironment.java
  src/test/java/com/birca/bircabackend/support/enviroment/ServiceTest.java
  src/test/resources/fixture/artist-fixture.sql
  src/test/resources/fixture/member-fixture.sql
Labels: FEAT

#21 [INFRA] 개발 서버 CD 구축
  .github/workflows/cd-dev.yml
  docker/Dockerfile-dev
  src/main/resources/application.yml
Labels: chore, infra

#18 [Feat] 사업자등록증 비즈니스 로직 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseProcessingService.java
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseService.java
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseStatusVerifier.java
  src/main/java/com/birca/bircabackend/command/cafe/application/OcrProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessAddress.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicense.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseRepository.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseCreateRequest.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseOcrRequest.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseOcrResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseStatusRequest.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseStatusResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/exception/BusinessLicenseErrorCode.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NationalTaxServiceBusinessLicenseStatusVerifier.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NationalTaxServiceVerificationApi.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NaverOcrApi.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NaverOcrProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/presentation/BusinessLicenseController.java
  src/main/resources/application-ci.yml
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/birca/bircabackend/command/cafe/acceptance/BusinessLicenseAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseProcessingServiceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseServiceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCodeTest.java
  src/test/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseTest.java
  src/test/java/com/birca/bircabackend/command/cafe/presentation/BusinessLicenseControllerTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/businessLicense.jpg
Labels: FEAT

#24 [FEAT] 생일 카페 등록 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/BircaBackendApplication.java
  src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeService.java
  src/main/java/com/birca/bircabackend/command/birca/domain/BirthdayCafe.java
  src/main/java/com/birca/bircabackend/command/birca/domain/BirthdayCafeRepository.java
  src/main/java/com/birca/bircabackend/command/birca/domain/Schedule.java
  src/main/java/com/birca/bircabackend/command/birca/domain/Visitants.java
  src/main/java/com/birca/bircabackend/command/birca/dto/BirthdayCafeCreateRequest.java
  src/main/java/com/birca/bircabackend/command/birca/exception/BirthdayCafeErrorCode.java
  src/main/java/com/birca/bircabackend/command/birca/presentation/BirthdayCafeController.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/birca/bircabackend/command/birca/acceptance/BirthdayCafeAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/birca/application/BirthdayCafeServiceTest.java
  src/test/java/com/birca/bircabackend/command/birca/domain/ScheduleTest.java
  src/test/java/com/birca/bircabackend/command/birca/domain/VisitantsTest.java
  src/test/java/com/birca/bircabackend/command/birca/presentation/BirthdayCafeControllerTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/fixture/birthday-cafe-fixture.sql
Labels: FEAT

#26 [ CHORE] 로그 관련 설정을 추가한다
  src/main/java/com/birca/bircabackend/common/log/CorrelationIdFilter.java
  src/main/java/com/birca/bircabackend/common/log/LogFilter.java
  src/main/java/com/birca/bircabackend/common/log/ThrowableCallable.java
  src/main/java/com/birca/bircabackend/common/log/ThrowableRunnable.java
  src/main/java/com/birca/bircabackend/common/log/TimeLogAspect.java
  src/main/java/com/birca/bircabackend/common/log/TimeLogPointCut.java
  src/main/java/com/birca/bircabackend/common/log/TimeLogTemplate.java
  src/main/resources/logback-spring.xml
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
Labels: chore

#29 [IFX] 카카오 로그인 로직 수정
  src/main/java/com/birca/bircabackend/command/auth/application/AuthService.java
  src/main/java/com/birca/bircabackend/command/auth/application/MemberAuthRepository.java
  src/main/java/com/birca/bircabackend/command/auth/application/oauth/OAuthMember.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/kakao/KakaoOAuthProvider.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/kakao/KakaoUserResponse.java
  src/main/java/com/birca/bircabackend/command/member/application/MemberService.java
  src/main/java/com/birca/bircabackend/command/member/domain/IdentityKey.java
  src/main/java/com/birca/bircabackend/command/member/domain/Member.java
  src/main/java/com/birca/bircabackend/command/member/domain/MemberRepository.java
  src/main/java/com/birca/bircabackend/command/member/domain/Nickname.java
  src/main/java/com/birca/bircabackend/command/member/exception/MemberErrorCode.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/logback-spring.xml
  src/main/resources/static/docs/api.html
  src/test/java/com/birca/bircabackend/command/auth/application/AuthServiceTest.java
  src/test/java/com/birca/bircabackend/command/member/application/MemberServiceTest.java
  src/test/java/com/birca/bircabackend/command/member/domain/MemberTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/MockOAuthEnvironment.java
  src/test/resources/fixture/artist-fixture.sql
  src/test/resources/fixture/birthday-cafe-fixture.sql
  src/test/resources/fixture/member-fixture.sql
Labels: fix

#27 [Feat] 사업자등록증 업로드 횟수 제한 기능
  src/main/java/com/birca/bircabackend/command/auth/AuthConfig.java
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseFacade.java
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseProcessingService.java
  src/main/java/com/birca/bircabackend/command/cafe/application/OcrProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicense.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/OcrRequestHistory.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/OcrRequestHistoryRepository.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseInfoResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/UploadCountResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/exception/BusinessLicenseErrorCode.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/NaverOcrProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountConfig.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountInterceptor.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountValidator.java
  src/main/java/com/birca/bircabackend/command/cafe/presentation/BusinessLicenseController.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/birca/bircabackend/command/cafe/acceptance/BusinessLicenseAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseProcessingServiceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountProviderTest.java
  src/test/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountValidatorTest.java
  src/test/java/com/birca/bircabackend/command/cafe/presentation/BusinessLicenseControllerTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/fixture/ocr-request-history-fixture.sql
Labels: FEAT

#33 [FEAT] 솔로 아티스트 조회
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/query/controller/ArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistDynamicRepository.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistDynamicRepositoryImpl.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistQueryRepository.java
  src/main/java/com/birca/bircabackend/query/service/ArtistQueryService.java
  src/main/resources/static/docs/api.html
  src/test/java/com/birca/bircabackend/query/acceptance/ArtistQueryAcceptanceTest.java
  src/test/java/com/birca/bircabackend/query/controller/ArtistQueryControllerTest.java
  src/test/java/com/birca/bircabackend/query/service/ArtistQueryServiceTest.java
  src/test/resources/fixture/artist-fixture.sql
Labels: FEAT

#32 [FEAT] 애플 로그인 구현
  src/main/java/com/birca/bircabackend/command/auth/application/token/JwtParseUtil.java
  src/main/java/com/birca/bircabackend/command/auth/application/token/JwtTokenProvider.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/OAuthConst.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/AppleAuthApi.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/AppleClaimValidator.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/AppleIdentityToken.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/AppleKeyResponse.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/AppleOAuthProvider.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/ApplePubKey.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/apple/EncryptUtil.java
  src/main/java/com/birca/bircabackend/command/auth/infrastructure/kakao/KakaoOAuthProvider.java
  src/main/java/com/birca/bircabackend/common/ApiResponseExtractor.java
  src/main/java/com/birca/bircabackend/common/exception/presentation/GlobalExceptionController.java
  src/main/resources/application-ci.yml
  src/main/resources/application-local.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/birca/bircabackend/command/auth/acceptance/AuthAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/auth/infrastructure/apple/AppleClaimValidatorTest.java
  src/test/java/com/birca/bircabackend/command/auth/token/JwtTokenProviderTest.java
  src/test/java/com/birca/bircabackend/common/JwtParseUtilTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
Labels: FEAT

#35 [REFACTOR] 사업자등록증 로직 수정
  src/main/java/com/birca/bircabackend/command/auth/AuthConfig.java
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseFacade.java
  src/main/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseProcessingService.java
  src/main/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountValidator.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/OcrRequestHistory.java
  src/main/java/com/birca/bircabackend/command/cafe/dto/BusinessLicenseInfoResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/nationaltaxservice/BusinessLicenseStatusRequest.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/nationaltaxservice/BusinessLicenseStatusResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/nationaltaxservice/NationalTaxServiceBusinessLicenseStatusVerifier.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/nationaltaxservice/NationalTaxServiceVerificationApi.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/naverocr/BusinessLicenseOcrRequest.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/naverocr/BusinessLicenseOcrResponse.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/naverocr/NaverOcrApi.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/naverocr/NaverOcrProvider.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountConfig.java
  src/main/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountInterceptor.java
  src/main/java/com/birca/bircabackend/command/cafe/presentation/BusinessLicenseController.java
  src/test/java/com/birca/bircabackend/command/cafe/acceptance/BusinessLicenseAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseProcessingServiceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountProviderTest.java
  src/test/java/com/birca/bircabackend/command/cafe/infrastructure/uploadcount/OcrRequestCountValidatorTest.java
  src/test/java/com/birca/bircabackend/query/controller/ArtistQueryControllerTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
Labels: refactor

#37 [REFACTOR] 사업자등록증 업로드 횟수 적용 변경
  src/main/java/com/birca/bircabackend/command/cafe/application/OcrRequestCountValidator.java
  src/main/resources/application-ci.yml
  src/main/resources/application-local.yml
Labels: refactor

#42 [FIX] 사업자등록증 번호 검증 수정
  .github/workflows/cd-dev.yml
  src/main/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCode.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/birca/bircabackend/command/cafe/application/BusinessLicenseServiceTest.java
  src/test/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseCodeTest.java
  src/test/java/com/birca/bircabackend/command/cafe/domain/BusinessLicenseTest.java
Labels: fix

#44 [FEAT] 최애/관심 아티스트 조회 기능
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/query/controller/FavoriteArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/controller/InterestArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/dto/ArtistResponse.java
  src/main/java/com/birca/bircabackend/query/repository/FavoriteArtistQueryRepository.java
  src/main/java/com/birca/bircabackend/query/repository/InterestArtistQueryRepository.java
  src/main/java/com/birca/bircabackend/query/service/FavoriteArtistQueryService.java
  src/main/java/com/birca/bircabackend/query/service/InterestArtistQueryService.java
  src/main/resources/static/docs/api.html
  src/test/java/com/birca/bircabackend/command/cafe/presentation/BusinessLicenseControllerTest.java
  src/test/java/com/birca/bircabackend/query/acceptance/FavoriteArtistQueryAcceptanceTest.java
  src/test/java/com/birca/bircabackend/query/acceptance/InterestArtistQueryAcceptanceTest.java
  src/test/java/com/birca/bircabackend/query/controller/FavoriteArtistQueryControllerTest.java
  src/test/java/com/birca/bircabackend/query/controller/InterestArtistQueryControllerTest.java
  src/test/java/com/birca/bircabackend/query/service/FavoriteArtistQueryServiceTest.java
  src/test/java/com/birca/bircabackend/query/service/InterestArtistQueryServiceTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/fixture/favorite-artist-fixture.sql
  src/test/resources/fixture/interest-artist-fixture.sql
Labels: FEAT

#47 [FEAT] 생일카페 대관 신청/취소 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/command/birca/application/BirthdayCafeService.java
  src/main/java/com/birca/bircabackend/command/birca/domain/BirthdayCafe.java
  src/main/java/com/birca/bircabackend/command/birca/domain/BirthdayCafeRepository.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/CongestionState.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/PhoneNumber.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/ProgressState.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/Schedule.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/SpecialGoodsStockState.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/Visibility.java
  src/main/java/com/birca/bircabackend/command/birca/domain/value/Visitants.java
  src/main/java/com/birca/bircabackend/command/birca/dto/ApplyRentalRequest.java
  src/main/java/com/birca/bircabackend/command/birca/dto/BirthdayCafeCreateRequest.java
  src/main/java/com/birca/bircabackend/command/birca/exception/BirthdayCafeErrorCode.java
  src/main/java/com/birca/bircabackend/command/birca/presentation/BirthdayCafeController.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/Cafe.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/birca/bircabackend/command/birca/acceptance/BirthdayCafeAcceptanceTest.java
  src/test/java/com/birca/bircabackend/command/birca/application/BirthdayCafeServiceTest.java
  src/test/java/com/birca/bircabackend/command/birca/domain/BirthdayCafeTest.java
  src/test/java/com/birca/bircabackend/command/birca/domain/value/PhoneNumberTest.java
  src/test/java/com/birca/bircabackend/command/birca/domain/value/ScheduleTest.java
  src/test/java/com/birca/bircabackend/command/birca/domain/value/VisitantsTest.java
  src/test/java/com/birca/bircabackend/command/birca/presentation/BirthdayCafeControllerTest.java
  src/test/resources/fixture/birthday-cafe-fixture.sql
Labels: FEAT

#48 [Feat] 아티스트/카페 검색 기능
  src/docs/asciidoc/api.adoc
  src/main/java/com/birca/bircabackend/command/artist/domain/Artist.java
  src/main/java/com/birca/bircabackend/command/artist/domain/ArtistGroup.java
  src/main/java/com/birca/bircabackend/command/cafe/domain/Cafe.java
  src/main/java/com/birca/bircabackend/query/controller/ArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/controller/CafeQueryController.java
  src/main/java/com/birca/bircabackend/query/controller/FavoriteArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/controller/InterestArtistQueryController.java
  src/main/java/com/birca/bircabackend/query/dto/ArtistSearchResponse.java
  src/main/java/com/birca/bircabackend/query/dto/CafeResponse.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistGroupQueryRepository.java
  src/main/java/com/birca/bircabackend/query/repository/ArtistQueryRepository.java
  src/main/java/com/birca/bircabackend/query/repository/CafeQueryRepository.java
  src/main/java/com/birca/bircabackend/query/service/ArtistSearchQueryService.java
  src/main/java/com/birca/bircabackend/query/service/CafeQueryService.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/birca/bircabackend/query/acceptance/ArtistQueryAcceptanceTest.java
  src/test/java/com/birca/bircabackend/query/acceptance/CafeAcceptanceTest.java
  src/test/java/com/birca/bircabackend/query/controller/ArtistQueryControllerTest.java
  src/test/java/com/birca/bircabackend/query/controller/CafeQueryControllerTest.java
  src/test/java/com/birca/bircabackend/query/service/ArtistQueryServiceTest.java
  src/test/java/com/birca/bircabackend/query/service/ArtistSearchQueryServiceTest.java
  src/test/java/com/birca/bircabackend/query/service/CafeQueryServiceTest.java
  src/test/java/com/birca/bircabackend/support/enviroment/DocumentationTest.java
  src/test/resources/fixture/birthday-cafe-fixture.sql
  src/test/resources/fixture/cafe-fixture.sql
  src/test/resources/fixture/search-artist-fixture.sql
Labels: FEAT
